# Generated by Django 4.2 on 2026-06-08 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        help_text="SHA-256 hashed 6-digit OTP code — never store raw OTPs",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Marked True after successful verification to prevent replay attacks",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="OTP expires 10 minutes after creation"
                    ),
                ),
                (
                    "attempt_count",
                    models.IntegerField(
                        default=0,
                        help_text="Failed verification attempts — lockout after 5 to prevent brute-force",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee who requested this OTP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Verification",
                "verbose_name_plural": "OTP Verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the employee saved this listing",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee who saved this listing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marketplace_listing",
                    models.ForeignKey(
                        help_text="The marketplace listing that was saved/wishlisted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="marketplace.marketplacelisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Product",
                "verbose_name_plural": "Saved Products",
                "ordering": ["-saved_at"],
                "unique_together": {("employee", "marketplace_listing")},
            },
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["employee", "is_used", "-created_at"],
                name="idx_otp_employee_lookup",
            ),
        ),
    ]
