# Generated by Django 4.2 on 2026-06-19 14:54

import bhel_connect_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_otpverification_savedproduct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="profile_picture",
            field=bhel_connect_backend.fields.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
