# Generated by Django 4.2 on 2026-06-08 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="HTTP method or logic action name (e.g., POST, DELETE, BULK_IMPORT)",
                        max_length=50,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        help_text="Name of the target database model affected",
                        max_length=100,
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Primary key of the affected model instance",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable detailed description of the administrative action"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the action was performed",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the admin user", null=True
                    ),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        help_text="The admin employee who performed this action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["admin_user", "-timestamp"], name="idx_audit_admin_time"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_model", "target_id"], name="idx_audit_target_lookup"
            ),
        ),
    ]
