# Generated by Django 4.2 on 2026-06-08 07:31

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category display name (e.g., Electronics, Vehicles)",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for filtering — must be unique",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower numbers display first in category lists",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category — null for top-level categories",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="marketplace.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Concise listing title — max 100 characters",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description — max 2000 characters",
                        max_length=2000,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Asking price in INR — minimum ₹1",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("like_new", "Like New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                        ],
                        help_text="Physical condition of the item",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Listing moderation and lifecycle status",
                        max_length=10,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Required when admin rejects — explains why to the seller",
                        null=True,
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the listing detail page was viewed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Product category for browsing and filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="marketplace.category",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Employee selling this item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Listing",
                "verbose_name_plural": "Marketplace Listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Vehicle make/brand (e.g., Maruti, Honda)",
                        max_length=50,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Vehicle model name (e.g., Swift, City)",
                        max_length=50,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Manufacturing year (1990-2030)",
                        validators=[
                            django.core.validators.MinValueValidator(1990),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
                (
                    "km_driven",
                    models.PositiveIntegerField(help_text="Total kilometers driven"),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("cng", "CNG"),
                        ],
                        help_text="Vehicle fuel type",
                        max_length=10,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")],
                        help_text="Vehicle transmission type",
                        max_length=10,
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        help_text="Parent marketplace listing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_details",
                        to="marketplace.marketplacelisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Listing Details",
                "verbose_name_plural": "Vehicle Listing Details",
            },
        ),
        migrations.CreateModel(
            name="PropertyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Property location/area description", max_length=200
                    ),
                ),
                (
                    "area_sqft",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total area in square feet",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of bedrooms — 0 for plots and commercial",
                    ),
                ),
                (
                    "bathrooms",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of bathrooms — 0 for plots"
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "Independent House"),
                            ("villa", "Villa"),
                            ("plot", "Plot/Land"),
                            ("commercial", "Commercial"),
                        ],
                        help_text="Type of property",
                        max_length=15,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("sale", "For Sale"), ("rent", "For Rent")],
                        help_text="For sale or for rent",
                        max_length=5,
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        help_text="Parent marketplace listing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_details",
                        to="marketplace.marketplacelisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Listing Details",
                "verbose_name_plural": "Property Listing Details",
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        help_text="Listing photo stored on Cloudinary CDN",
                        max_length=255,
                        verbose_name="image",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary image shown in listing cards and search results",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        help_text="The listing this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="marketplace.marketplacelisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Image",
                "verbose_name_plural": "Listing Images",
                "ordering": ["-is_primary", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message content — max 1000 characters",
                        max_length=1000,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the message was sent"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the receiver has read this message",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        help_text="The listing this conversation is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="marketplace.marketplacelisting",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="Employee who receives the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="Employee who sent the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="marketplacelisting",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_listing_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacelisting",
            index=models.Index(
                fields=["status", "price"], name="idx_listing_status_price"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacelisting",
            index=models.Index(
                fields=["category", "status"], name="idx_listing_category_status"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacelisting",
            index=models.Index(
                fields=["seller", "status"], name="idx_listing_seller_status"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["listing", "timestamp"], name="idx_chat_listing_time"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["receiver", "is_read"], name="idx_chat_receiver_read"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["listing", "sender", "receiver"], name="idx_chat_conversation"
            ),
        ),
    ]
