# Generated by Django 4.2 on 2026-06-19 14:54

import bhel_connect_backend.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingimage",
            name="image",
            field=bhel_connect_backend.fields.CloudinaryField(
                help_text="Listing photo stored on Cloudinary CDN",
                max_length=255,
                verbose_name="image",
            ),
        ),
        migrations.CreateModel(
            name="MarketplaceListingView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of the unique view"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        help_text="The marketplace listing that was viewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views",
                        to="marketplace.marketplacelisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The employee who viewed the listing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewed_marketplace_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Listing View",
                "verbose_name_plural": "Marketplace Listing Views",
            },
        ),
        migrations.AddIndex(
            model_name="marketplacelistingview",
            index=models.Index(
                fields=["listing", "user"], name="marketplace_listing_333a87_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketplacelistingview",
            constraint=models.UniqueConstraint(
                fields=("listing", "user"), name="unique_listing_user_view"
            ),
        ),
    ]
