# Generated by Django 4.2 on 2026-06-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0002_alter_listingimage_image_marketplacelistingview_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacelisting",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="DateTime when the listing expires and becomes inactive",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketplacelisting",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="pending",
                help_text="Listing moderation and lifecycle status",
                max_length=10,
            ),
        ),
    ]
