# Generated by Django 4.2 on 2026-06-08 07:31

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Campaign title shown to employees", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed product description, specifications, and terms"
                    ),
                ),
                (
                    "product_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Product image for campaign display",
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(
                        help_text="Total units available in this campaign"
                    ),
                ),
                (
                    "available_quantity",
                    models.PositiveIntegerField(
                        help_text="Remaining units — use select_for_update() when modifying"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        help_text="Campaign duration in days from start_date"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="When the campaign starts accepting registrations"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        help_text="Auto-calculated: start_date + duration_days"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Campaign lifecycle status",
                        max_length=10,
                    ),
                ),
                (
                    "upi_qr_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="UPI QR code image for manual payment fallback",
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin employee who created this campaign",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the employee registered"
                    ),
                ),
                (
                    "token_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Token amount (10%% of price at registration time) — immutable once set",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current payment status",
                        max_length=10,
                    ),
                ),
                (
                    "cashfree_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Cashfree payment gateway order identifier",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "cashfree_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="Cashfree payment identifier — set on webhook confirmation",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "payment_approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of payment approval/rejection",
                        null=True,
                    ),
                ),
                (
                    "is_waitlisted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if employee is waitlisted (no slot available at registration time)",
                    ),
                ),
                (
                    "waitlist_position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Queue position in waitlist — null if not waitlisted",
                        null=True,
                    ),
                ),
                (
                    "cancellation_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the employee cancelled — null if not cancelled",
                        null=True,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Refund amount calculated based on cancellation timing",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not Applicable"),
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                        ],
                        default="not_applicable",
                        help_text="Current refund processing status",
                        max_length=15,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="Campaign the employee registered for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="smartbuy.campaign",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee who registered for this campaign",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved/rejected the payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Registration",
                "verbose_name_plural": "Campaign Registrations",
                "ordering": ["-reservation_date"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Vendor company or business name", max_length=200
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Primary contact person at the vendor", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Vendor business email", max_length=100
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Vendor contact phone number", max_length=15
                    ),
                ),
                (
                    "products_provided",
                    models.TextField(
                        help_text="Description of products/services this vendor supplies"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive vendors are hidden from new campaign creation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TokenPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Token payment amount in INR",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "cashfree_order_id",
                    models.CharField(
                        help_text="Unique Cashfree order identifier",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "cashfree_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="Cashfree payment ID — set on successful payment",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the payment was initiated"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Payment verification status",
                        max_length=10,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the payment was reviewed by admin",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Required explanation when rejecting a payment",
                        null=True,
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        help_text="The campaign registration this payment covers",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_payment",
                        to="smartbuy.campaignregistration",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Payment",
                "verbose_name_plural": "Token Payments",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_buyers",
                    models.PositiveIntegerField(
                        help_text="Minimum confirmed buyers for this price tier"
                    ),
                ),
                (
                    "max_buyers",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum confirmed buyers for this tier — null means no upper limit",
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit for this buyer range",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="Campaign this tier belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_tiers",
                        to="smartbuy.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Tier",
                "verbose_name_plural": "Pricing Tiers",
                "ordering": ["min_buyers"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="vendor",
            field=models.ForeignKey(
                help_text="Vendor supplying this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="smartbuy.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="tokenpayment",
            index=models.Index(
                fields=["status", "-submitted_at"], name="idx_payment_status_date"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricingtier",
            unique_together={("campaign", "min_buyers")},
        ),
        migrations.AddIndex(
            model_name="campaignregistration",
            index=models.Index(
                fields=["campaign", "payment_status"], name="idx_reg_campaign_payment"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignregistration",
            index=models.Index(
                fields=["campaign", "is_waitlisted", "waitlist_position"],
                name="idx_reg_waitlist",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaignregistration",
            unique_together={("campaign", "employee")},
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_campaign_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "end_date"], name="idx_campaign_status_end"
            ),
        ),
    ]
