# Generated by Django 4.2 on 2026-06-08 14:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbuy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignregistration',
            name='slot_expiry_date',
            field=models.DateTimeField(blank=True, help_text='Deadline to confirm reservation when promoted from waitlist', null=True),
        ),
        migrations.AddField(
            model_name='campaignregistration',
            name='upi_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Screenshot of UPI payment deposit', max_length=255, null=True, verbose_name='image'),
        ),
    ]
