# Generated by Django 4.2 on 2026-06-19 14:54

import bhel_connect_backend.fields
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartbuy", "0002_campaignregistration_slot_expiry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="product_image",
            field=bhel_connect_backend.fields.CloudinaryField(
                blank=True,
                help_text="Product image for campaign display",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="upi_qr_image",
            field=bhel_connect_backend.fields.CloudinaryField(
                blank=True,
                help_text="UPI QR code image for manual payment fallback",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="campaignregistration",
            name="upi_screenshot",
            field=bhel_connect_backend.fields.CloudinaryField(
                blank=True,
                help_text="Screenshot of UPI payment deposit",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price per unit for this buyer range",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="tokenpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Token payment amount in INR",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
