# Generated by Django 4.2 on 2026-06-24 14:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartbuy", "0003_alter_campaign_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="cancellation_refund_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Custom refund amount returned to the employee upon cancellation during active phase",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="token_deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Custom token deposit amount required to join this campaign",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="campaignregistration",
            name="token_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Token amount paid/to be paid for this registration — immutable once set",
                max_digits=10,
            ),
        ),
    ]
