# Generated by Django 4.2 on 2026-06-08 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the notification", max_length=100
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Detailed content message of the notification",
                        max_length=500,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if the notification has been read by the user",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("campaign", "Campaign Update"),
                            ("payment", "Payment Update"),
                            ("listing", "Listing Moderation"),
                            ("chat", "New Chat Message"),
                            ("system", "System Notification"),
                        ],
                        default="system",
                        help_text="Categorization of the notification type",
                        max_length=20,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Optional deep link/path (e.g., /smartbuy/12) for redirection on click",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this notification was created",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Employee who receives this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="idx_notif_user_unread",
            ),
        ),
    ]
